# Generated by Django 4.2.4 on 2023-11-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('premedics', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_no', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_no', models.CharField(max_length=100)),
            ],
        ),
    ]
