# Generated by Django 4.2.4 on 2023-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediform',
            name='address',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
