# Generated by Django 4.2.4 on 2023-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mediform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
