# Generated by Django 4.2.4 on 2023-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mediform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediform',
            name='guardian_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mediform',
            name='hospital_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
